-- initialize Employee table
INSERT INTO PUBLIC.EMPLOYEE (EMP_ID,EMAIL,FNAME,LNAME,SALARY,TITLE,VERSION)
VALUES (1,'john@gmail.com','John','Jason',1000.00,'student',1);

-- Initialize SECURITY_USER table
INSERT INTO PUBLIC.SECURITY_USER (USER_ID,USERNAME,EMP_ID)
VALUES (1,'user1',1);
INSERT INTO PUBLIC.SECURITY_USER (USER_ID,USERNAME)
VALUES (2,'admin');

-- alter password for SECURITY_USER table 
UPDATE PUBLIC.SECURITY_USER
SET PWHASH='PBKDF2WithHmacSHA256:2048:7iBe7ElNsy7qQqVtBub9YXttmZ0DDYuQkCFDrkqKVHk=:2sTwehNNWt0dzSw6X8U3ZSG3FiEu0sG60DZHMRKVn6k='
WHERE USER_ID=1;
UPDATE PUBLIC.SECURITY_USER
SET PWHASH='PBKDF2WithHmacSHA256:2048:9yKxNL6KNVUJxSVmWhRWJFOBGy4RHE7VMEdr1HQ+2fA=:O6Obmq7B7Tix5EPiJ+Dt+ZLKLkD+qKvrpE9YDB+nphQ='
WHERE USER_ID=2;


-- Initialize SECURITY_ROLE table
INSERT INTO PUBLIC.SECURITY_ROLE (ROLE_ID,ROLENAME)
VALUES (1,'USER_ROLE');
INSERT INTO PUBLIC.SECURITY_ROLE (ROLE_ID,ROLENAME)
VALUES (2,'ADMIN_ROLE');


-- Initialize SECURITY_USER_SECURITY_ROLE table
INSERT INTO PUBLIC.SECURITY_USER_SECURITY_ROLE (ROLE_ID,USER_ID)
VALUES (1,1);
INSERT INTO PUBLIC.SECURITY_USER_SECURITY_ROLE (ROLE_ID,USER_ID)
VALUES (2,2);

-- Initial Phone table
INSERT INTO PUBLIC.PHONE (PHONE_ID,PHONE_TYPE,AREACODE,PHONENUMBER,VERSION,OWNING_EMP_ID,MAP_COORDS,PROVIDER)
VALUES (1,'H','613','-111-1111',1,1,'','Rogers');
INSERT INTO PUBLIC.PHONE (PHONE_ID,PHONE_TYPE,AREACODE,PHONENUMBER,VERSION,OWNING_EMP_ID,MAP_COORDS)
VALUES (2,'M','613','-222-2222',1,1,'map coords');
